version: '1.0.2.{build}'
branches:
  only:
    - dev
    - /v1.0.2/
environment:
  matrix:
    - TOXENV: "py36"
      TOXPYTHON: "C:\\Python36-x64\\python.exe"
      PYTHON_HOME: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

    - TOXENV: "py37"
      TOXPYTHON: "C:\\Python37-x64\\python.exe"
      PYTHON_HOME: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"

    - TOXENV: "py38"
      TOXPYTHON: "C:\\Python38-x64\\python.exe"
      PYTHON_HOME: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"

    - TOXENV: "py38"
      TOXPYTHON: "C:\\Python38\\python.exe"
      PYTHON_HOME: "C:\\Python38"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "32"

init:
  - "ECHO %TOXENV%"
  - "ECHO %TOXPYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
  - "%TOXPYTHON% C:/get-pip.py"
  - "%PYTHON_HOME%/Scripts/pip.exe install -r requirements-appveyor.txt"

build: false

test_script:
  - "%PYTHON_HOME%\\Scripts\\tox -e %TOXENV%"
